todo/urls.py
from django.urls import path
from .views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskStatusUpdateView,
)


app_name = "todo"

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:task_id>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:task_id>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "task/<int:task_id>/update-status/",
        TaskStatusUpdateView.as_view(),
        name="task-status-update",
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/<int:tag_id>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:tag_id>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-created_at"]

    def __str__(self):
        return self.content

todo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from todo.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = (
            "content",
            "deadline",
            "is_done",
            "tags",
        )
        widgets = {
            "deadline": forms.DateInput(
                attrs={"type": "date", "class": "form-control"}
            )
        }

    def clean_deadline(self):
        deadline = self.cleaned_data.get("deadline")
        if deadline and deadline.date() < timezone.now().date():
            raise ValidationError("The deadline cannot be in the past")

        return deadline

todo/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from todo.forms import TaskForm
from todo.models import Task, Tag


class TaskListView(ListView):
    model = Task
    paginate_by = 7


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")

    def get_object(self, queryset=None) -> Task:
        task_id = self.kwargs.get("task_id")
        return get_object_or_404(Task, id=task_id)


class TaskDeleteView(DeleteView):
    model = Task
    template_name = "todo/task_confirm_delete.html"
    success_url = reverse_lazy("todo:task-list")

    def get_object(self, queryset=None) -> Task:
        task_id = self.kwargs.get("task_id")
        return get_object_or_404(Task, id=task_id)


class TagListView(ListView):
    model = Tag
    paginate_by = 7


class TagCreateView(CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")

    def get_object(self, queryset=None) -> Tag:
        tag_id = self.kwargs.get("tag_id")
        return get_object_or_404(Tag, id=tag_id)


class TagDeleteView(DeleteView):
    model = Tag
    template_name = "todo/tag_confirm_delete.html"
    success_url = reverse_lazy("todo:tag-list")

    def get_object(self, queryset=None) -> Tag:
        tag_id = self.kwargs.get("tag_id")
        return get_object_or_404(Tag, id=tag_id)


class TaskStatusUpdateView(View):
    def post(self, request, task_id) -> HttpResponse:
        task = get_object_or_404(Task, id=task_id)
        task.is_done = not task.is_done
        task.save()
        return redirect("todo:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Todo list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
          {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
          {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url "todo:task-list" %}">Home</a></li>
  <li class="list-group-item"><a href="{% url "todo:tag-list" %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag</h1>

  <p>Are you sure you want to delete the tag: <strong>{{ tag.name }}</strong></p>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Confirm" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

      <input class="btn btn-primary" type="submit" value="Confirm">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}


{% block content %}
  <h1>
    Tags
    <a href="{% url "todo:tag-create" %}" class="btn btn-primary link-to-page">Add</a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a href="{% url "todo:tag-update" tag_id=tag.id %}" class="btn btn-secondary">Update</a></td>
        <td><a href="{% url "todo:tag-delete" tag_id=tag.id %}" class="btn btn-secondary">Delete</a></td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no tags on this page.</p>
    {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task</h1>

  <p>Are you sure you want to delete the task: <strong>{{ task.content }}</strong></p>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Confirm" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

      <input class="btn btn-primary" type="submit" value="Confirm">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}


{% block content %}
  <h1>
    TODO list
    <a href="{% url "todo:task-create" %}" class="btn btn-primary link-to-page">Add task</a>
  </h1>

  {% for task in task_list %}
    <div class="border-bottom mb-4 p-3">
      {% if task.is_done %}
        <form action="{% url 'todo:task-status-update' task_id=task.id %}" method="POST" class="d-inline">
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary link-to-page">Undo</button>
        </form>
      {% else %}
        <form action="{% url 'todo:task-status-update' task_id=task.id %}" method="POST" class="d-inline">
          {% csrf_token %}
          <button type="submit" class="btn btn-success link-to-page">Complete</button>
        </form>
      {% endif %}
      <h5>
        {{ task.content }}
        {% if task.is_done %}
          <span class="text-success">Done</span>
        {% else %}
          <span class="text-danger">Not done</span>
        {% endif %}
      </h5>
      <p class="small">
        Created: {{ task.created_at }}
        <span class="text-brown">
          Deadline: {% if task.deadline %}{{ task.deadline }}{% else %}this task has no deadline.{% endif %}
        </span>
      </p>
      <p class="text-muted">
        Tags:
        {% for tag in task.tags.all %}
          <span>{{ tag }}</span>
        {% endfor %}
        <a href="{% url "todo:task-update" task_id=task.id %}">Update</a>
        <a href="{% url "todo:task-delete" task_id=task.id %}">Delete</a>
      </p>
    </div>
  {% endfor %}


{% endblock %}